image: node:9.5

cache:
  untracked: true
  key: "$CI_PROJECT_ID"
  paths:
    - .yarn

before_script:
  - yarn config set cache-folder .yarn
  - yarn install 

stages:
  - lint

code lint:
  stage: lint
  script:
    - npx tslint -c tslint.json -p tsconfig.json 'src/**/*.ts'